#!/usr/bin/env python3
"""
S01 Brand Builder - 品牌建構師
Single brand architecture.
"""
import os
import sys
import datetime
import json
import argparse

# === 動態路徑設定：確保專案根目錄在 sys.path 中 ===
# 這使得無論從哪個目錄執行腳本，都能正確導入模組
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from agents.core import BaseAgent
from utils.vector_db_manager import vector_db
# YouTube crawler removed - no longer needed
from typing import Dict, Any

class S01BrandBuilder(BaseAgent):
    """
    S01 Brand Builder - 品牌建構師
    
    架構設計：
    - 🧠 Antigravity: 分析品牌資訊，生成品牌指南內容 (執行 .agent/workflows/s01_brand_builder.md)
    - 🧠 Antigravity: 分析品牌資訊，生成品牌指南內容 (執行 .agent/workflows/s01_brand_builder.md)
    - ⚙️ Python: 檔案寫入、LanceDB 同步
    """
    
    def __init__(self):
        super().__init__(name="S01_BrandBuilder")
        self.brand_profile = self._load_brand_profile()
        default_path = "docs/brand_guideline.md"
        self.guideline_path = self.brand_profile.get("file_paths", {}).get("guideline_path", default_path)

    def _load_brand_profile(self) -> Dict[str, Any]:
        """Loads the brand profile JSON."""
        if hasattr(self, "brand") and getattr(self, "brand", None):
            return self.brand.brand_config or {}
        return {}

    def _verify_outputs(self, action: str):
        """Verifies that expected assets depend on the action."""
        missing = []
        brand_name = self.brand.slug
        
        if action == "generate_assets":
            css_path = f"outputs/{brand_name}/assets/brand_style.css"
            if not os.path.exists(css_path):
                missing.append(css_path)
                
        if action == "collect_data":
            # Check if YouTube raw data was created (if configured)
            if self.brand_profile.get("youtube_video_urls"):
                yt_dir = f"outputs/{brand_name}/raw_data"
                if not os.path.exists(yt_dir) or not any(f.endswith(".json") or f.endswith(".txt") for f in os.listdir(yt_dir)):
                     # This is a loose check, mainly to ensure directory isn't empty
                     pass 

        if missing:
             self.log_activity(f"CRITICAL WARNING: Missing expected outputs: {missing}")

    def run(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Manages the lifecycle of brand guidelines.
        """
        action = input_data.get("action", "create")
        
        result = {}
        # 如果沒有指定 action，但有品牌資料，則預設為 create
        if "core_values" in input_data:
            result = self._create_guideline(input_data)
        elif action == "create":
            result = self._create_guideline(input_data)
        elif action == "update":
            result = self._update_guideline(input_data)
        elif action == "sync":
            result = self._sync_to_db()
        elif action == "collect_data":
            result = self._collect_data()
        elif action == "generate_assets":
            result = self._generate_assets()
        else:
            result = {"status": "error", "message": f"Unknown action: {action}"}
            
        self._verify_outputs(action)
        return result

    def _create_guideline(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Creates the initial brand guideline.
        
        執行流程：
        1. ⚙️ Python: 準備輸入資料
        2. 🧠 ANTIGRAVITY_WORKFLOW: 執行 s01_brand_builder.md 生成指南內容
        2. 🧠 ANTIGRAVITY_WORKFLOW: 執行 s01_brand_builder.md 生成指南內容
        3. ⚙️ Python: 寫入檔案並同步至 LanceDB
        """
        self.log_activity("Creating brand guideline...")
        
        # ⚙️ Step 1: Python 準備資料
        brand_data = {
            "core_values": data.get('core_values', 'To be defined'),
            "tone_voice": data.get('tone_voice', 'Professional, Authoritative, yet Accessible'),
            "persona": data.get('persona', 'General Audience'),
            "dos_donts": data.get('dos_donts', '- Do: Be clear\n- Don\'t: Use jargon')
        }
        
        # 🧠 Step 2: ANTIGRAVITY_WORKFLOW 執行點
        # 檢查是否由 Antigravity 傳入已生成的內容
        if "generated_content" in data:
            self.log_activity("Using content generated by Antigravity Workflow.")
            content = data["generated_content"]
        else:
            # Fallback: 使用臨時模板
            self.log_activity("No external content provided. Using fallback template.")
            content = self._generate_guideline_fallback(brand_data)
        
        # ⚙️ Step 3: Python 寫入檔案
        try:
            os.makedirs(os.path.dirname(self.guideline_path), exist_ok=True)
            with open(self.guideline_path, "w") as f:
                f.write(content)
                
            self.log_activity(f"Brand guideline created at {self.guideline_path}")
            
            # Auto-sync after creation
            self._sync_to_db()
            
            return {"status": "success", "message": "Brand guideline created and synced."}
            
        except Exception as e:
            self.log_activity(f"Error creating guideline: {e}")
            return {"status": "error", "message": str(e)}

    def _collect_data(self) -> Dict[str, Any]:
        """
        Orchestrates the data collection process.
        NOTE: YouTube crawler has been removed.
        """
        self.log_activity("Starting automated data collection...")
        results = {}
        
        # Placeholder for future data collection sources
        self.log_activity("Data collection completed. No active collectors configured.")

        return {
            "status": "success",
            "message": "Data collection completed.",
            "details": results
        }

    def _generate_assets(self) -> Dict[str, Any]:
        """Generates brand assets like CSS."""
        self.log_activity("Generating brand assets...")
        
        assets_dir = f"outputs/{self.brand.slug}/assets"
        os.makedirs(assets_dir, exist_ok=True)
        
        # 1. Generate brand_style.css
        css_content = self._generate_css()
        css_path = f"{assets_dir}/brand_style.css"
        with open(css_path, "w", encoding="utf-8") as f:
            f.write(css_content)
            
        self.log_activity(f"Generated brand_style.css at {css_path}")
        
        return {
            "status": "success",
            "message": "Brand assets generated.",
            "files": [css_path]
        }

    def _generate_css(self) -> str:
        """Generates CSS content based on brand profile."""
        brand_name = self.brand_profile.get("brand_identity", {}).get("name", self.brand.slug)
        visual = self.brand_profile.get("visual_identity", {})
        colors = visual.get("color_palette", {})
        
        primary = colors.get("primary", "#1E3A5F")
        secondary = colors.get("secondary", "#4A90D9")
        accent = colors.get("accent", "#FF6B35")
        neutral = colors.get("neutral", "#333333")
        background = "#F8F9FA" # Default light background

        return f"""/**
 * {brand_name} - 品牌樣式表
 * Generated by S01 Brand Builder
 * 
 * 配色方案:
 * - Primary: {primary}
 * - Secondary: {secondary}
 * - Accent: {accent}
 * - Neutral: {neutral}
 * - Background: {background}
 */

/* ========================================
   1. 基礎設定 (Base Settings)
   ======================================== */
:root {{
  /* 品牌色彩 */
  --color-primary: {primary};
  --color-secondary: {secondary};
  --color-accent: {accent};
  --color-neutral: {neutral};
  --color-background: {background};
  --color-white: #FFFFFF;
  --color-light-gray: #E9ECEF;
  --color-border: #DEE2E6;
  
  /* 字體設定 */
  --font-family-base: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans TC", sans-serif;
  --font-size-base: 17px;
  --font-size-small: 15px;
  --font-size-large: 19px;
  --font-size-h1: 32px;
  --font-size-h2: 26px;
  --font-size-h3: 21px;
  
  /* 行高 */
  --line-height-base: 1.75;
  --line-height-heading: 1.35;
  
  /* 間距 */
  --spacing-xs: 0.5rem;
  --spacing-sm: 1rem;
  --spacing-md: 1.5rem;
  --spacing-lg: 2rem;
  --spacing-xl: 3rem;
  
  /* 圓角 */
  --border-radius: 8px;
  --border-radius-lg: 12px;
}}

/* ========================================
   2. Typography 排版
   ======================================== */
body {{
  font-family: var(--font-family-base);
  font-size: var(--font-size-base);
  line-height: var(--line-height-base);
  color: var(--color-neutral);
  background-color: var(--color-background);
}}

h1, h2, h3, h4, h5, h6 {{
  font-weight: 700;
  line-height: var(--line-height-heading);
  color: var(--color-primary);
  margin-top: var(--spacing-xl);
  margin-bottom: var(--spacing-md);
}}

h1 {{
  font-size: var(--font-size-h1);
  margin-top: 0;
}}

h2 {{
  font-size: var(--font-size-h2);
  padding-bottom: var(--spacing-sm);
  border-bottom: 2px solid var(--color-secondary);
}}

h3 {{
  font-size: var(--font-size-h3);
  color: var(--color-secondary);
}}

p {{
  margin-top: 0;
  margin-bottom: var(--spacing-md);
}}

a {{
  color: var(--color-secondary);
  text-decoration: none;
  transition: color 0.2s ease;
}}

a:hover {{
  color: var(--color-primary);
  text-decoration: underline;
}}

/* ========================================
   3. Components 元件
   ======================================== */

/* Highlight Box */
.brand-highlight,
blockquote {{
  background-color: rgba(74, 144, 217, 0.08); /* Fallback tint needed? Using hardcoded for now or derived? */
  border-left: 4px solid var(--color-secondary);
  padding: var(--spacing-md) var(--spacing-lg);
  margin: var(--spacing-lg) 0;
  border-radius: 0 var(--border-radius) var(--border-radius) 0;
}}

/* CTA Box */
.brand-cta {{
  background-color: var(--color-primary);
  color: var(--color-white);
  padding: var(--spacing-lg);
  border-radius: var(--border-radius-lg);
  text-align: center;
  margin: var(--spacing-xl) 0;
}}

.brand-cta a {{
  display: inline-block;
  background-color: var(--color-accent);
  color: var(--color-white);
  padding: var(--spacing-sm) var(--spacing-lg);
  border-radius: var(--border-radius);
  font-weight: 600;
  text-decoration: none;
}}

.brand-cta a:hover {{
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}}

/* Info Box */
.brand-info {{
  background-color: var(--color-light-gray);
  border-radius: var(--border-radius);
  padding: var(--spacing-md);
  margin: var(--spacing-lg) 0;
}}

/* Table */
table {{
  width: 100%;
  border-collapse: collapse;
  margin: var(--spacing-lg) 0;
}}

th, td {{
  padding: var(--spacing-sm) var(--spacing-md);
  text-align: left;
  border-bottom: 1px solid var(--color-border);
}}

th {{
  background-color: var(--color-primary);
  color: var(--color-white);
  font-weight: 600;
}}

img {{
  max-width: 100%;
  height: auto;
  border-radius: var(--border-radius);
}}
"""

    def _generate_guideline_fallback(self, data: Dict[str, Any]) -> str:
        """
        臨時 fallback 方法，產生簡單的品牌指南模板。
        
        ⚠️ 此方法將在整合 Antigravity workflow 呼叫機制後移除。
        正式版本應由 Antigravity 執行 .agent/workflows/s01_brand_builder.md
        """
        return f"""# Brand Guideline

## Core Values
{data.get('core_values')}

## Tone & Voice
{data.get('tone_voice')}

### Voice Characteristics
- Professional and authoritative
- Accessible and friendly
- Data-driven and precise

## Target Audience
{data.get('persona')}

### Audience Persona
- **Demographics**: To be defined based on business context
- **Psychographics**: Values knowledge and expertise
- **Pain Points**: Information overload, unclear guidance
- **Goals**: Make informed decisions efficiently

## Do's and Don'ts

{data.get('dos_donts')}

## Writing Style Examples

### Example 1: Explaining Technical Concepts
**Good**: "Our platform uses machine learning to analyze patterns, helping you make data-driven decisions."
**Bad**: "We leverage cutting-edge AI paradigms to synergize actionable insights."

### Example 2: Addressing Users
**Good**: "您可以根據自己的行程安排，靈活選擇最適合的景點套票。"
**Bad**: "使用者被賦予權限根據其組織需求配置介面參數。"

---
*Generated by S01 Brand Builder*
*Last updated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""

    def _update_guideline(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Updates the brand guideline."""
        self.log_activity("Updating brand guideline...")
        # Implementation for update logic
        return {"status": "success", "message": "Brand guideline updated."}

    def _sync_to_db(self) -> Dict[str, Any]:
        """Syncs the brand guideline to the Style DB."""
        self.log_activity("Syncing brand guideline to Style DB...")
        
        if not os.path.exists(self.guideline_path):
            return {"status": "error", "message": "Brand guideline file not found."}
            
        with open(self.guideline_path, "r", encoding="utf-8") as f:
            content = f.read()
        
        # 將 Markdown 按 H2 標題切分
        sections = self._split_by_h2(content)
        
        # 同步至 LanceDB Style DB
        items = []
        for idx, section in enumerate(sections):
            section_id = f"brand_guideline_section_{idx}"
            items.append({
                "id": section_id,
                "document": section["content"],
                "metadata": {
                    "id": section_id,
                    "type": "guideline",
                    "section": section["title"],
                    "source": "brand_guideline.md",
                    "status": "publish",
                    "date": datetime.datetime.now().isoformat(),
                    "modified": datetime.datetime.now().isoformat()
                }
            })
            
        vector_db.upsert_style_batch(items)
        
        self.log_activity(f"Synced {len(sections)} sections to Style DB")
        
        return {
            "status": "success", 
            "message": f"Brand guideline synced to Style DB ({len(sections)} sections).",
            "sections_stored": len(sections)
        }
    
    def _split_by_h2(self, markdown: str) -> list:
        """
        將 Markdown 按 H2 標題切分成多個段落
        
        Returns:
            [{"title": "章節標題", "content": "完整內容"}, ...]
        """
        sections = []
        current_section = {"title": "Introduction", "content": ""}
        
        for line in markdown.split("\n"):
            if line.startswith("## "):
                # 遇到新的 H2，儲存當前段落
                if current_section["content"].strip():
                    sections.append(current_section)
                # 開始新段落
                current_section = {
                    "title": line.replace("## ", "").strip(),
                    "content": line + "\n"
                }
            else:
                current_section["content"] += line + "\n"
        
        # 儲存最後一個段落
        if current_section["content"].strip():
            sections.append(current_section)
        
        return sections

# Global instance
s01_brand_builder = S01BrandBuilder()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="S01 Brand Builder CLI")
    parser.add_argument("--action", default="collect_data", help="Action to perform (create, update, sync, collect_data)")
    parser.add_argument("--data", help="JSON string of data for the action")
    
    args = parser.parse_args()
    
    # 1. Prepare Data
    input_data = {}
    if args.data:
        try:
            input_data = json.loads(args.data)
        except json.JSONDecodeError as e:
            print(json.dumps({"status": "error", "message": f"Invalid JSON in --data: {e}"}))
            sys.exit(1)
            
    # If action is passed via CLI args, override/set it in input_data
    if args.action:
        input_data["action"] = args.action
        
    # 2. Run Agent
    try:
        # Re-initialize agent to pick up new settings
        s01_brand_builder = S01BrandBuilder()
        result = s01_brand_builder.run(input_data)
        print(json.dumps(result, ensure_ascii=False, indent=2))
    except Exception as e:
        print(json.dumps({
            "status": "error",
            "message": str(e)
        }, ensure_ascii=False))
        sys.exit(1)
