from agents.core import BaseAgent, PathResolver, resolve_path
from utils.vector_db_manager import vector_db
from typing import Dict, Any, List
import os
import asyncio
import json
from bs4 import BeautifulSoup
from crawl4ai import AsyncWebCrawler

class P01KeywordStrategist(BaseAgent):
    """
    P01 Keyword Strategist - 關鍵字策略師
    
    架構設計：
    - ⚙️ Python: Google Search 爬取、Crawl4AI 爬取、LanceDB 查詢
    - 🧠 Antigravity: 分析爬取結果，生成關鍵字策略 (執行 .agent/workflows/p01_keyword_strategist.md)
    - ⚙️ Python: 儲存策略結果
    """
    
    def __init__(self):
        super().__init__(name="P01_KeywordStrategist")
        self.brand_profile = self.brand.brand_config or {}
        self.brand_name = self.brand.slug
        self.resolver = PathResolver(get_brand_manager() if 'get_brand_manager' in globals() else None)
        # Default to zh-TW if not specified
        self.target_language = self.brand_profile.get("content_strategy", {}).get("language", "zh-TW")


    def run(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Conducts keyword research and strategy.
        """
        topic = input_data.get("topic", "")
        self.log_activity(f"Researching keywords for topic: {topic}")
        
        # ⚙️ Step 1: Python 查詢現有內容 (Content DB)
        existing_content = vector_db.query_content(
            query_text=topic,
            n_results=3
        )
        self.log_activity(f"Found related existing articles in DB.")
        
        # ⚙️ Step 1.5: 查詢品牌風格 (Style DB)
        # LanceDB 這裡我們可以簡單合併查詢，或只查其中一個核心概念
        brand_style = vector_db.query_style_rules(
            query_text="品牌核心 目標受眾 語氣",
            n_results=3
        )
        self.log_activity(f"Retrieved brand style context.")
        
        # ⚙️ Step 1.6: 讀取網站結構 (Site Structure)
        site_structure = {}
        try:
            structure_path = self.resolver.resolve("outputs/{BRAND_NAME}/raw_data/site_structure.json")
            if structure_path.exists():
                with open(structure_path, "r", encoding="utf-8") as f:
                    site_structure = json.load(f)
                self.log_activity(f"Loaded site structure.")
        except Exception as e:
            self.log_activity(f"Warning: Could not load site structure: {e}")
        
        # ⚙️ Step 2: Python 爬取競爭對手 (使用 Crawl4AI 搜尋 + 爬取)
        # 由於 _search_competitors 改為 async，我們需要整合執行
        async def execute_search_and_crawl():
            urls = await self._search_competitors(topic, language=self.target_language)
            self.log_activity(f"Found {len(urls)} competitor URLs via Crawl4AI.")
            data = await self._crawl_competitors(urls)
            return urls, data

        competitor_urls, competitor_data = asyncio.run(execute_search_and_crawl())
        self.log_activity(f"Crawled {len(competitor_data)} competitor pages.")
        
        # 🔥 Step 3: Cluster Scanner 雙軌重複性檢查
        import subprocess
        scan_results = {}
        try:
            self.log_activity(f"Running Cluster Scanner for topic: {topic}")
            # 注意：這裡使用 shell=False 安全執行，並確保 PYTHONPATH
            env = os.environ.copy()
            env["PYTHONPATH"] = os.getcwd() # Ensure root is in path
            env["BRAND_NAME"] = self.brand_name
            
            # 使用 sys.executable 確保使用同一個 python 解譯器 (即 venv 中的)
            import sys
            result = subprocess.run(
                [sys.executable, "utils/cluster_scanner.py", "--topic", topic, "--mode", "any"],
                capture_output=True,
                text=True,
                env=env,
                check=False 
            )
            
            if result.returncode == 0:
                # 嘗試從 stdout 中提取 JSON (移除可能的日誌干擾)
                output = result.stdout.strip()
                if "{" in output:
                    json_start = output.find("{")
                    json_end = output.rfind("}") + 1
                    try:
                        scan_results = json.loads(output[json_start:json_end])
                    except:
                        self.log_activity(f"Failed to parse scanner JSON: {output}")
                self.log_activity(f"Cluster Scanner completed. Recommendation: {scan_results.get('recommendation')}")
            else:
                self.log_activity(f"Cluster Scanner failed: {result.stderr}")
                
        except Exception as e:
            self.log_activity(f"Error running Cluster Scanner: {e}")


        # 🧠 Step 4: ANTIGRAVITY_WORKFLOW 執行點
        if "generated_strategy" in input_data:
            self.log_activity("Using strategy generated by Antigravity Workflow.")
            strategy = input_data["generated_strategy"]
        else:
            self.log_activity("No external strategy provided. Using fallback template.")
            # 傳入 scan_results 供參考
            strategy = self._generate_strategy_fallback(topic, competitor_data, existing_content, brand_style, site_structure, scan_results)
        
        # Save context for Antigravity
        context_data = {
            "topic": topic,
            "existing_content": existing_content,
            "brand_style": brand_style,
            "site_structure": site_structure,
            "competitor_data": competitor_data,
            "cluster_scan_results": scan_results # 🔥 Inject Scan Results
        }
        
        context_path = self.resolver.resolve("outputs/{BRAND_NAME}/raw_data/p01_context.json")
        context_path.parent.mkdir(parents=True, exist_ok=True)
        
        try:
            with open(context_path, "w", encoding="utf-8") as f:
                json.dump(context_data, f, ensure_ascii=False, indent=2, default=str)
            self.log_activity(f"Saved context data to {context_path}")
        except Exception as e:
            self.log_activity(f"Error saving context data: {e}")

        # Save strategy as well (for fallback)
        strategy_path = self.resolver.resolve("outputs/{BRAND_NAME}/strategies/topic_cluster_{TOPIC_SLUG}.json", TOPIC_SLUG=topic.replace(' ', '-').lower())
        strategy_path.parent.mkdir(parents=True, exist_ok=True)
        with open(strategy_path, "w", encoding="utf-8") as f:
            json.dump(strategy, f, ensure_ascii=False, indent=2)

        return {"status": "success", "strategy": strategy, "context_path": context_path}

    async def _search_competitors(self, topic: str, num_results: int = 3, language: str = "zh-TW") -> List[str]:
        """
        Searches Google for top competitors using Crawl4AI.
        """
        urls = []
        try:
            # Map simple language codes to Google hl param if needed
            hl_param = language
            if language == "Traditional Chinese" or language == "zh-TW":
                 hl_param = "zh-TW"
            elif language == "English" or language == "en-US":
                 hl_param = "en"

            # 建構 Google 搜尋 URL
            search_url = f"https://www.google.com/search?q={topic}&num={num_results + 2}&hl={hl_param}" # 多抓一點備用
            
            async with AsyncWebCrawler(verbose=False) as crawler:
                result = await crawler.arun(url=search_url)
                
                if result.success:
                    soup = BeautifulSoup(result.html, 'html.parser')
                    
                    # 解析 Google 搜尋結果
                    # 策略: 尋找包含 h3 (標題) 的 a 標籤，這是較穩定的特徵
                    for link in soup.find_all('a'):
                        # 檢查連結內是否有 h3 標題
                        if link.find('h3'):
                            url = link.get('href')
                            
                            if url and url.startswith('http') and 'google' not in url and 'youtube' not in url:
                                # 移除可能的 Google 追蹤參數 (雖然直接 href 通常是乾淨的)
                                urls.append(url)
                                
                        if len(urls) >= num_results:
                            break
                else:
                    self.log_activity(f"Failed to crawl Google SERP: {result.error_message}")

            return urls
        except Exception as e:
            self.log_activity(f"Error searching Google with Crawl4AI: {e}")
            return []

    async def _crawl_competitors(self, urls: List[str]) -> List[Dict[str, Any]]:
        """Crawls competitor pages using Crawl4AI."""
        results = []
        if not urls:
            return results
            
        try:
            async with AsyncWebCrawler(verbose=False) as crawler:
                for url in urls:
                    try:
                        result = await crawler.arun(url=url)
                        if result.success:
                            results.append({
                                "url": url,
                                "content": result.markdown[:2000] # Limit content size for LLM
                            })
                    except Exception as e:
                        self.log_activity(f"Error crawling {url}: {e}")
        except Exception as e:
             self.log_activity(f"Error initializing crawler: {e}")
             
        return results

    def _generate_strategy_fallback(self, topic: str, competitor_data: List[Dict[str, Any]], existing_content: Any, brand_style: Any, site_structure: Dict[str, Any], scan_results: Dict[str, Any]) -> Dict[str, Any]:
        """
        臨時 fallback 方法，產生簡單的關鍵字策略。
        """
        # 簡單的 fallback 邏輯
        primary_keyword = topic.strip()
        secondary_keywords = [
            f"{primary_keyword} guide",
            f"{primary_keyword} tips",
            f"best {primary_keyword}"
        ]

        # 🚀 SMART FALLBACK: Respect Scanner Results
        recommendation = "create_new"
        existing_info = {}
        target_pillar = {}

        if scan_results and scan_results.get("recommendation") == "optimize_existing":
            candidates = scan_results.get("candidates", [])
            if candidates:
                best_match = candidates[0] # Scanner sorts by relevance
                recommendation = "optimize_existing_pillar"
                
                # Fill duplication check with real data found by scanner
                existing_info = {
                    "has_similar_content": True,
                    "similarity_score": best_match.get("similarity", 0.9),
                    "existing_articles": [{
                        "id": best_match.get("id"),
                        "title": best_match.get("title"),
                        "url": best_match.get("link"),
                        "similarity": best_match.get("similarity", 0.9),
                        "content_type": "Pillar Page" # Assumption for fallback
                    }],
                    "recommendation": "optimize_existing_pillar",
                    "recommendation_reason": f"System automatically detected existing content: {best_match.get('title')}"
                }
                
                # Pre-fill Pillar Page info from existing
                target_pillar = {
                    "title": best_match.get("title"), 
                    "id": best_match.get("id"),
                    "slug": best_match.get("slug"),
                    "main_keyword": primary_keyword
                }

        base_strategy = {
            "primary_keyword": primary_keyword,
            "secondary_keywords": secondary_keywords,
            "search_intent": "Informational",
            "competitor_analysis": f"Found {len(competitor_data)} competitors covering this topic.",
            "content_gap": "Detailed analysis pending Antigravity workflow integration.",
            "suggested_title": f"The Ultimate Guide to {primary_keyword}",
            "target_audience_segment": "General audience interested in " + primary_keyword,
            "keyword_difficulty": "Medium",
            "search_volume_estimate": "Medium",
            "cluster_pages": [
                {"title": f"{primary_keyword}: 必去景點推薦", "main_keyword": f"{primary_keyword} 景點", "slug": "attractions-guide", "category": "Travel", "intent": "Informational", "link_back_anchor": "Attractions"},
                {"title": f"{primary_keyword}: 在地美食攻略", "main_keyword": f"{primary_keyword} 美食", "slug": "food-guide", "category": "Food", "intent": "Informational", "link_back_anchor": "Food Guide"},
                {"title": f"{primary_keyword}: 住宿精選", "main_keyword": f"{primary_keyword} 住宿", "slug": "accommodation-guide", "category": "Accommodation", "intent": "Commercial", "link_back_anchor": "Accommodation Guide"}
            ] 
        }
        
        # 🚀 AUTOMATED CLUSTER AUDIT (Step 6.5)
        # Iterate through proposed cluster pages and verify against site structure
        import subprocess
        import sys
        
        updated_clusters = []
        for cluster in base_strategy.get("cluster_pages", []):
            cluster_topic = cluster["main_keyword"]
            # Extract core topic from title if keyword is generic English
            if "住宿" in cluster["title"]: cluster_topic = "住宿推薦"
            if "交通" in cluster["title"]: cluster_topic = "交通攻略"
            if "景點" in cluster["title"]: cluster_topic = "必去景點"
            
            try:
                # Run scanner for this cluster topic
                check_res = subprocess.run(
                    [sys.executable, "utils/cluster_scanner.py", "--topic", cluster_topic, "--mode", "any"],
                    capture_output=True, text=True, env=os.environ.copy()
                )
                if check_res.returncode == 0:
                    # 嘗試從 stdout 中提取 JSON
                    check_output = check_res.stdout.strip()
                    if "{" in check_output:
                        json_start = check_output.find("{")
                        json_end = check_output.rfind("}") + 1
                        try:
                            scan_data = json.loads(check_output[json_start:json_end])
                            if scan_data.get("recommendation") == "optimize_existing":
                                candidates = scan_data.get("candidates", [])
                                if candidates:
                                    existing = candidates[0]
                                    cluster["status"] = "EXISTING"
                                    cluster["existing_url"] = existing.get("link")
                                    cluster["title"] = f"[EXISTING] {existing.get('title')}"
                                    self.log_activity(f"Detected existing cluster page: {existing.get('title')}")
                        except:
                            self.log_activity(f"Failed to parse cluster scanner JSON: {check_output}")
            except Exception as e:
                self.log_activity(f"Cluster dedupe check failed: {e}")
            
            updated_clusters.append(cluster)
            
        base_strategy["cluster_pages"] = updated_clusters
        
        # Merge Smart Fallback Data
        if recommendation == "optimize_existing_pillar":
            base_strategy["duplication_check"] = existing_info
            base_strategy["pillar_page"] = target_pillar
            base_strategy["suggested_title"] = f"[OPTIMIZE] {target_pillar['title']}"
            
        return base_strategy

# Global instance
p01_keyword_strategist = P01KeywordStrategist()

if __name__ == "__main__":
    import sys
    import argparse
    
    parser = argparse.ArgumentParser(description='P01 Keyword Strategist')
    parser.add_argument('--topic', type=str, required=True, help='Topic to analyze')
    args = parser.parse_args()
    
    try:
        result = p01_keyword_strategist.run({"topic": args.topic})
        print(json.dumps(result, ensure_ascii=False, indent=2, default=str))
    except Exception as e:
        print(json.dumps({"status": "error", "message": str(e)}, ensure_ascii=False))
        sys.exit(1)
